name: Training
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Build the app
        run: | 
          npm i
          npm run build
          ls dist
