name: Training
on: [workflow_dispatch]

permissions: 
  contents: write

env:
  PW: ${{secrets.DB_PW}}

jobs:
  test-job:
    if:  PW == 'qwerty123'
    runs-on: ubuntu-latest
    steps:
      - name: Do some
        run: echo 'Hello'
           
