name: Training
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git code
        uses: actions/checkout@v5
      - name: Checkt file listing
        run: cat README.md
