name: Training
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Run JS code
        run: node code.js
