name: Training
on: [push]

permissions: 
  contents: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git code
        uses: actions/checkout@v5
      - name: Build the app
        run: | 
           touch info.txt
           git config user.name 'repenaattori'
           git config user.email 'reimarii@oamk.fi'
           git add info.txt
           git commit -m  'Info added'
           git push
           
