name: Training
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git code
        uses: actions/checkout@v5
      - name: Build the app
        run: | 
           touch info.txt
           git add info.txt
           git commit -m  'Info added'
           git push
           
