name: Training
on: [workflow_dispatch]

permissions: 
  contents: write

jobs:
  test-job:
    if:  ${{secrets.DB_PW == 'qwerty123'}}
    runs-on: ubuntu-latest
    steps:
      - name: Do some
        run: echo 'Hello'
           
