name: Training
on: [workflow_dispatch]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git code
        uses: actions/checkout@v5
      - name: Checkt file listing
        run: ls -a
